/*
 * Copyright 2013 Trustees of the University of Pennsylvania
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.upenn.cis.db.mefview.services;

import static com.google.common.base.Preconditions.checkNotNull;

/**
 * Exceptions from the server generated by our application which make it to the
 * client are converted to this.
 * 
 * @author John Frommeyer
 * 
 */
public class IeegWsRemoteAppException extends IeegWsRemoteException {
	private static final long serialVersionUID = 1L;
	private final String errorCode;
	private final String errorId;
	private final String hostname;

	public IeegWsRemoteAppException(String msg, String errorCode,
			String errorId, String hostname) {
		super(msg);
		this.errorCode = checkNotNull(errorCode);
		this.errorId = checkNotNull(errorId);
		this.hostname = checkNotNull(hostname);
	}

	/**
	 * @return the errorCode
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * @return the errorId
	 */
	public String getErrorId() {
		return errorId;
	}

	/**
	 * @return the hostname
	 */
	public String getHostname() {
		return hostname;
	}

}
